spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mw88s80ocwgk4w84scwkw84o:3306/default?ssl-mode=REQUIRED}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:mysql}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:mQvRHM2eWfuF4GlqlNn94J3iy8hCRzEMymO2f3fwEVmpgV53FCXWPCCZ4bwIcmRA}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

app.base-url=${APP_BASE_URL:http://209.126.86.149:8083}
